#!/usr/bin/env python3

import os

from exjobb.webapp import webapp

app = webapp.create_app()
os.environ["FLASK_ENV"] = "development"
os.environ["FLASK_DEBUG"] = "True"
app.run(host="0.0.0.0", port=8000)
