#!/usr/bin/env python3

import sys
import os

dir_root = os.path.join("exjobb","tex")
input_dir_base = sys.argv[1:][0]

sections = [
  "title",
  "abstract_en",
  "abstract_sv",
  "introduction",
  "theory",
  "methods",
  "results",
  "analysis",
  "discussion",
  "conclusion",
  "references",
  "appendices",
]

dir_base = os.path.join(dir_root, input_dir_base)
if not os.path.exists(dir_base):
  os.makedirs(dir_base)

text_main = [
  r"\documentclass{article}",
  r"\input{preamble.tex}",
  r"",
  r"\begin{document}",
]

for i, section in enumerate(sections):
  name_file = f"{i:02d}_{section}.tex"
  text_main.append(fr"  \input{{{name_file}}}")
  text_main.append( r"  \newpage")
  path_file = os.path.join(dir_base, name_file)
  with open(path_file, 'w') as fh:
    fh.write(fr"\head{{{section.split('_')[0].title()}}}")
    fh.write(os.linesep)

with open(os.path.join(dir_base, f"{input_dir_base}.tex"), 'w') as fh:
  fh.write(os.linesep.join(text_main+[r"\end{document}"]))
