#!/usr/bin/env python3

import sys
import os

name_project = sys.argv[1:][0]
dir_root = os.path.join("exjobb", "webapp", "templates", name_project)

sections = [
  "title",
  "abstract_en",
  "abstract_sv",
  "introduction",
  "theory",
  "methods",
  "results",
  "analysis",
  "discussion",
  "conclusion",
  "references",
  "appendices",
]

if not os.path.exists(dir_root):
  os.makedirs(dir_root)

for i, section in enumerate(sections):
  name_file = f"{i:02d}_{section}.html"
  path_file = os.path.join(dir_root, name_file)
  with open(path_file, 'w') as fh:
    fh.write(fr"<h2> {section.split('_')[0].title()} </h2>")
    fh.write(os.linesep)
    fh.write('<link rel="stylesheet" href="{{ url_for("static", filename="style.css") }}">')
    fh.write(os.linesep)
